version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn -B verify

workflows:
  build:
    jobs:
      - build