version: 2.1

orbs:
  codecov: codecov/codecov@3.3.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B clean compile
      - run:
          name: Test with Coverage
          command: mvn -B test
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  build:
    jobs:
      - build