version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B clean compile
      - run:
          name: Test
          command: mvn -B test

workflows:
  build:
    jobs:
      - build